server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/bibliotheque
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.hibernate.ddl-auto=update
hibernate.format_sql=true;